import { Dimensions, StyleSheet } from 'react-native'
import R from '@app/assets/R'
import {
  colors,
  dimensions,
  fonts,
  HEIGHT,
  styleView,
  WIDTH,
} from '@theme/index'

const { width, height } = Dimensions.get('window')
const scale = width / 375
export default StyleSheet.create({
  main: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 40 * scale,
    marginTop: 20,
  },
  txtLogin: {
    fontSize: 18 * scale,
    lineHeight: 26 * scale,
    color: colors.blue,
    textAlign: 'center',
    marginTop: 5 * scale,
    fontFamily: R.fonts.sf_semi_bold,
  },
  viewName: {
    marginTop: 25 * scale,
    flexDirection: 'row',
    // backgroundColor: 'yellow'
  },
  txtField: {
    fontFamily: R.fonts.sf_regular,
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 18 * scale,
    color: '#262626',
  },
  txtOr: {
    fontFamily: R.fonts.sf_regular,
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 20 * scale,
    color: '#262626',
    alignSelf: 'center',
    marginTop: 16 * scale,
  },
  txtError: {
    fontFamily: R.fonts.sf_regular,
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 22 * scale,
    color: 'red',
    marginLeft: 35 * scale,
  },
  txtIconRed: {
    fontFamily: R.fonts.sf_regular,
    fontStyle: 'normal',
    fontSize: 14 * scale,
    lineHeight: 22 * scale,
    color: '#F03E3E',
    marginLeft: 4 * scale,
  },
  viewTextInput: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15 * scale,
  },
  iconName: {
    width: 16 * scale,
    height: 18 * scale,
  },
  iconPhone: {
    width: 24 * scale,
    height: 24 * scale,
  },
  txtInput: {
    marginLeft: 15 * scale,
    width: 250 * scale,
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_regular,
  },
  txtInputPassWord: {
    marginLeft: 15 * scale,
    width: 246 * scale,
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_regular,
  },
  viewLine: {
    borderWidth: 1 * scale,
    borderColor: '#1290CC',
    width: 295 * scale,
    marginTop: 10 * scale,
  },
  btnRegister: {
    width: 290 * scale,
    height: 45 * scale,
    backgroundColor: colors.primary,
    borderRadius: 8 * scale,
    marginTop: 40 * scale,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    // marginBottom: 30 * scale,
  },
  btnRegister2: {
    width: 290 * scale,
    height: 50 * scale,
    borderRadius: 50 * scale,
    marginTop: 16 * scale,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 1 * scale,
    borderColor: '#F03E3E',
    marginBottom: 40 * scale,
  },
  txtRegister: {
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_semi_bold,
    fontStyle: 'normal',
    textAlign: 'center',
    color: '#FAFAFA',
    lineHeight: 21 * scale,
  },
  txtRegister2: {
    fontSize: 16 * scale,
    lineHeight: 21 * scale,
    fontFamily: R.fonts.sf_semi_bold,
    fontStyle: 'normal',
    textAlign: 'center',
    color: '#F03E3E',
  },
  viewName2: {
    marginTop: 16 * scale,
    flexDirection: 'row',
  },
  btnShow: {
    width: 24 * scale,
    height: 24 * scale,
  },
  iconLock: {
    width: 16 * scale,
    height: 20 * scale,
  },
  txtForgotPass: {
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_regular,
    lineHeight: 22 * scale,
    alignSelf: 'flex-end',
    color: '#F03E3E',
    marginTop: 16 * scale,
  },
  imageLogin: {
    alignSelf: 'center',
    width: 203 * scale,
    height: 40 * scale,
    marginTop: 100 * scale,
    marginBottom: 60 * scale,
    backgroundColor: 'transparent',
  },
  iconShow: {
    width: 24 * scale,
    height: 24 * scale,
  },
  labelInput: {
    ...fonts.regular14,
    fontWeight: '400',
    color: '#595959',
    marginBottom: 10 * scale,
  },
  inputContainer: {
    paddingHorizontal: 0,
  },
  txtSupport: {
    textAlign: 'right',
    paddingRight: 15,
    fontSize: 16 * scale,
    lineHeight: 22 * scale,
    color: colors.gray,
    marginTop: 8 * scale,
    fontFamily: R.fonts.sf_regular,
    textDecorationLine: 'underline',
    textDecorationColor: colors.gray,
  },
  phoneinfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 15 * scale,
  },
  info: {
    fontFamily: R.fonts.sf_regular,
    fontSize: 16 * scale,
    color: colors.blue,
    lineHeight: 21 * scale,
    marginLeft: 5 * scale,
  },
  description: {
    fontFamily: R.fonts.sf_regular,
    fontSize: 16 * scale,
    color: colors.gray,
    paddingHorizontal: 40 * scale,
    lineHeight: 21 * scale,
    marginBottom: 15 * scale,
  },
  dropdown: {
    // margin: 16,
    minHeight: 40,
    borderBottomColor: '#8C8C8C',
    borderBottomWidth: 1,
  },
  placeholderStyle: {
    ...fonts.regular16,
    color: '#8C8C8C',
    marginLeft: 6,
  },
  selectedTextStyle: {
    ...fonts.regular16,
    color: colors.text.primary,
    marginLeft: 6,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  titleProvice: {
    ...fonts.regular14,
    color: '#595959',
    marginBottom: 4,
  },
})
