export const ROOT_STACK = {
  MAIN_APP: 'MAIN_APP',
  GLOBAL_ALERT: 'GLOBAL_ALERT',
  GLOBAL_CONFIRM: 'GLOBAL_CONFIRM',
}

export const SCREEN_ROUTER = {
  MAIN: 'MAIN',
  AUTH: 'AUTH',
  SPLASH: 'SPLASH',
}

export const MAIN_TAB = {
  HOME: 'HOME',
  PRODUCT: 'PRODUCT',
  ODER: 'ODER',
  ACCOUNT: 'ACCOUNT',
}

export const SCREEN_ROUTER_AUTH = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  PASSWORD: 'PASSWORD',
  // FORGOT_PASS: 'FORGOT_PASS',
  // OTP: 'OTP',
  // UPDATE_PASS: 'UPDATE_PASS',
  // LIST_SHOP_FOLLOW: 'LIST_SHOP_FOLLOW',
  // PASSWORD: 'PASSWORD',
  PROVINCE_LOGIN: 'PROVINCE_LOGIN',
  SUPPORT: 'SUPPORT',
}

export const SCREEN_ROUTER_APP = {
  HOME: 'HOME',
  PRODUCT: 'PRODUCT',
  ORDER: 'ORDER',
  DEBIT: 'DEBIT',
  ACCOUNT: 'ACCOUNT',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  MEDIA_VIEWER: 'MEDIA_VIEWER',
  CART: 'CART',
  PAYMENT: 'PAYMENT',
  VOUCHER: 'VOUCHER',
  SELECT_RECEIVER: 'SELECT_RECEIVER',
  RECEIVER_EDIT: 'RECEIVER_EDIT',
  CHANGE_PASS: 'CHANGE_PASS',
  ORDER_DETAIL: 'ORDER_DETAIL',
  FILTER_SEARCH: 'FILTER_SEARCH',
  VOUCHER_DETAIL: 'VOUCHER_DETAIL',
  PAYMENT_TYPE: 'PAYMENT_TYPE',
  USER_INFO: 'USER_INFO',
  NEWS: 'NEWS',
  NEWS_DETAIL: 'NEWS_DETAIL',
  SURVEY: 'SURVEY',
  POINT: 'POINT',
  NOTIFICATION: 'NOTIFICATION',
}
