import { colors, fonts, styleView } from '@app/theme'
import { StyleSheet } from 'react-native'
import { getBottomSpace, isIphoneX } from 'react-native-iphone-x-helper'

export const styles = StyleSheet.create({
  bottomView: {
    ...styleView.rowItemBetween,
    width: '100%',
    //height: 65 + getBottomSpace(),
    // padding: 20,
    backgroundColor: colors.white,
    alignItems: 'center',
    //marginTop: 7,
    paddingBottom: isIphoneX() ? getBottomSpace() : 0,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  btnOrder: {
    ...styleView.centerItem,
    height: 52,
    maxWidth: '50%',
    flex: 1,
    backgroundColor: colors.primary,
  },
  itemImg: {
    width: 72,
    height: 72,
    borderRadius: 4,
    marginRight: 12,
  },
  inforView: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    marginTop: 5,
    marginBottom: 8,
  },
  giftViewContainer: {
    ...styleView.rowItemBetween,
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.white,
    marginTop: 8,
  },
  vTotalMoney: {
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 15,
  },
  orderItemView: {
    ...styleView.rowItem,
    alignItems: 'center',
    // paddingHorizontal: 15,
    //marginHorizontal: 16,
    marginBottom: 1,
    // borderBottomWidth: 1,
    //borderColor: colors.v_line,
    //paddingBottom: 9,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  txtTotal: { ...fonts.regular16, color: colors.text.dark },
  txtPriceTotal: { ...fonts.semi_bold16, color: colors.primary },
  txtBtnOrder: {
    ...fonts.medium16,
    color: colors.white,
  },
  icMap: {
    width: 20,
    height: 20,
    alignSelf: 'flex-start',
    marginRight: 8,
  },
  viewInfoReceiver: { flex: 1, justifyContent: 'space-between' },
  txtInfoReceiver: { ...fonts.semi_bold16, color: colors.text.primary },
  viewAddressInfo: {
    ...styleView.rowItemBetween,
    alignItems: 'center',
    marginTop: 6,
  },
  txtAddress: {
    ...fonts.regular16,
    color: colors.text.dark,
    flex: 1,
  },
  icArrow: { width: 20, height: 20, marginLeft: 10 },
  phoneAddress: {
    ...fonts.regular15,
    marginTop: 6,
    color: colors.text.dark,
  },
  icOrder: { width: 24, height: 24 },
  txtOrderInfo: {
    ...fonts.semi_bold16,
    marginLeft: 8,
    color: colors.text.primary,
  },
  txtTotalAmount: { ...fonts.regular16, color: colors.text.primary },
  txtPriceAmount: { ...fonts.semi_bold16, color: colors.primary },
  viewPrice: {
    backgroundColor: colors.white,
    marginTop: 8,
    paddingTop: 20,
    paddingBottom: 10,
  },
  txtNotiSale: {
    ...fonts.regular16,
    color: '#FF544D',
    textAlign: 'center',
  },
  viewLine: {
    ...styleView.rowItemBetween,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  titleLine: { ...fonts.regular16, color: colors.text.dark },
  containerItem: {
    ...styleView.rowItem,
    alignItems: 'center',
    // marginBottom: 6,
    paddingVertical: 16,
    marginHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.v_line,
  },
  txtNameProduct: {
    ...fonts.medium16,
    color: colors.text.primary,
  },
  viewPriceProduct: {
    flex: 1,
    alignItems: 'center',
    ...styleView.rowItemBetween,
    marginTop: 8,
  },
  txtPriceProduct: {
    ...fonts.regular16,
    color: colors.primary,
  },
  txtAmount: {
    ...fonts.regular16,
    color: colors.text.dark,
  },
  textLineThrough: {
    fontSize: 12,
    marginLeft: 6,
    color: colors.text.light,
    textDecorationLine: 'line-through',
  },
  tagDiscount: {
    marginLeft: 4,
    padding: 3,
    backgroundColor: colors.brand,
    borderRadius: 4,
    // position: 'absolute',
    // right: 0,
  },
})
