import I18n from '@app/i18n/i18n'
function strings() {
  return {
    cancel: I18n.t('cancel', { defaultValue: '' }),
    confirm: I18n.t('confirm', { defaultValue: '' }),
    notification: I18n.t('notification', { defaultValue: '' }),
    re_login: I18n.t('re_login', { defaultValue: '' }),
    try_again: I18n.t('try_again', { defaultValue: '' }),
    account: I18n.t('account', { defaultValue: '' }),
    home: I18n.t('home', { defaultValue: '' }),
    noti: I18n.t('noti', { defaultValue: '' }),
    canceled: I18n.t('canceled', { defaultValue: '' }),
    list_address: I18n.t('list_address', { defaultValue: '' }),
    number_not_validate: I18n.t('number_not_validate', { defaultValue: '' }),
    add_address: I18n.t('add_address', { defaultValue: '' }),
    profile: I18n.t('profile', { defaultValue: '' }),
    receiver_address: I18n.t('receiver_address', { defaultValue: '' }),
    email: I18n.t('email', { defaultValue: '' }),
    cancel_order_successfully: I18n.t('cancel_order_successfully', {
      defaultValue: '',
    }),
    type_email: I18n.t('type_email', { defaultValue: '' }),
    order: I18n.t('order', { defaultValue: '' }),
    product: I18n.t('product', { defaultValue: '' }),
    buy_amount: I18n.t('buy_amount', { defaultValue: '' }),
    type_survey_content: I18n.t('type_survey_content', { defaultValue: '' }),
    survey_content: I18n.t('survey_content', { defaultValue: '' }),
    apply_promo_successfully: I18n.t('apply_promo_successfully', {
      defaultValue: '',
    }),
    rank_product: I18n.t('rank_product', { defaultValue: '' }),
    not_duplicate_with_password: I18n.t('not_duplicate_with_password', {
      defaultValue: '',
    }),
    require_login_message: I18n.t('require_login_message', {
      defaultValue: '',
    }),
    confirm_logout: I18n.t('confirm_logout', { defaultValue: '' }),
    news: I18n.t('news', { defaultValue: '' }),
    download_image_successfully: I18n.t('download_image_successfully', {
      defaultValue: '',
    }),
    loading_progress: I18n.t('loading_progress', { defaultValue: '' }),
    login: I18n.t('login', { defaultValue: '' }),
    forgotPass: I18n.t('forgotPass', { defaultValue: '' }),
    sign_up: I18n.t('sign_up', { defaultValue: '' }),
    mail_sign_up: I18n.t('mail_sign_up', { defaultValue: '' }),
    send: I18n.t('send', { defaultValue: '' }),
    otp_mess: I18n.t('otp_mess', { defaultValue: '' }),
    network_error: I18n.t('network_error', { defaultValue: '' }),
    cart: I18n.t('cart', { defaultValue: '' }),
    total_money: I18n.t('total_money', { defaultValue: '' }),
    payment: I18n.t('payment', { defaultValue: '' }),
    set_address_default: I18n.t('set_address_default', { defaultValue: '' }),
    save: I18n.t('save', { defaultValue: '' }),
    full_name: I18n.t('full_name', { defaultValue: '' }),
    type_name: I18n.t('type_name', { defaultValue: '' }),
    phone: I18n.t('phone', { defaultValue: '' }),
    type_phone: I18n.t('type_phone', { defaultValue: '' }),
    app_crash: I18n.t('app_crash', { defaultValue: '' }),
    please_report: I18n.t('please_report', { defaultValue: '' }),
    restart_app: I18n.t('restart_app', { defaultValue: '' }),
    see_more: I18n.t('see_more', { defaultValue: '' }),
    search: I18n.t('search', { defaultValue: '' }),
    product_hot: I18n.t('product_hot', { defaultValue: '' }),
    search_product: I18n.t('search_product', { defaultValue: '' }),
    category: I18n.t('category', { defaultValue: '' }),
    product_sale: I18n.t('product_sale', { defaultValue: '' }),
    event: I18n.t('event', { defaultValue: '' }),
    user_survey: I18n.t('user_survey', { defaultValue: '' }),
    messenger: I18n.t('messenger', { defaultValue: '' }),
    please_input_email: I18n.t('please_input_email', { defaultValue: '' }),
    email_not_validate: I18n.t('email_not_validate', { defaultValue: '' }),
    please_input_survey_content: I18n.t('please_input_survey_content', {
      defaultValue: '',
    }),
    zalo: I18n.t('zalo', { defaultValue: '' }),
    hotline: I18n.t('hotline', { defaultValue: '' }),
    sellect_all: I18n.t('sellect_all', { defaultValue: '' }),
    please_select_product: I18n.t('please_select_product', {
      defaultValue: '',
    }),
    delete_address: I18n.t('delete_address', {
      defaultValue: '',
    }),
    delete_address_successfully: I18n.t('delete_address_successfully', {
      defaultValue: '',
    }),
    edit: I18n.t('edit', { defaultValue: '' }),
    search_receiver: I18n.t('search_receiver', { defaultValue: '' }),
    order_success: I18n.t('order_success', { defaultValue: '' }),
    receiver_info: I18n.t('receiver_info', { defaultValue: '' }),
    please_select_receiver: I18n.t('please_select_receiver', {
      defaultValue: '',
    }),
    promotion_code: I18n.t('promotion_code', { defaultValue: '' }),
    promotion: I18n.t('promotion', { defaultValue: '' }),
    select_promotion_code: I18n.t('select_promotion_code', {
      defaultValue: '',
    }),

    transfer_momo: I18n.t('transfer_momo', { defaultValue: '' }),
    cash: I18n.t('cash', { defaultValue: '' }),
    transfer: I18n.t('transfer', { defaultValue: '' }),
    VNPay: I18n.t('VNPay', { defaultValue: '' }),
    point_store: I18n.t('point_store', { defaultValue: '' }),
    point: I18n.t('point', { defaultValue: '' }),
    use_point: I18n.t('use_point', { defaultValue: '' }),
    confirm_cancel_order: I18n.t('confirm_cancel_order', { defaultValue: '' }),
    you_need_select_address: I18n.t('you_need_select_address', {
      defaultValue: '',
    }),
    you_need_select_payments: I18n.t('you_need_select_payments', {
      defaultValue: '',
    }),
    are_you_order: I18n.t('are_you_order', { defaultValue: '' }),
    payment_on_delivery: I18n.t('payment_on_delivery', { defaultValue: '' }),
    payment_via_VN_pay: I18n.t('payment_via_VN_pay', { defaultValue: '' }),
    info_account: I18n.t('info_account', { defaultValue: '' }),
    delete_account: I18n.t('delete_account', { defaultValue: '' }),
    payments: I18n.t('payments', { defaultValue: '' }),
    select_payments: I18n.t('select_payments', { defaultValue: '' }),
    select_promo_code: I18n.t('select_promo_code', { defaultValue: '' }),
    total_amount: I18n.t('total_amount', { defaultValue: '' }),
    type_password: I18n.t('type_password', { defaultValue: '' }),
    password: I18n.t('password', { defaultValue: '' }),
    product_stop_sell: I18n.t('product_stop_sell', { defaultValue: '' }),
    buyNow: I18n.t('buyNow', { defaultValue: '' }),
    product_out_of_stock: I18n.t('product_out_of_stock', { defaultValue: '' }),
    select_province: I18n.t('select_province', { defaultValue: '' }),
    select_districts: I18n.t('select_districts', { defaultValue: '' }),
    select_wards: I18n.t('select_wards', { defaultValue: '' }),
    add_receiver: I18n.t('add_receiver', { defaultValue: '' }),
    edit_receiver: I18n.t('edit_receiver', { defaultValue: '' }),
    province: I18n.t('province', { defaultValue: '' }),
    districts: I18n.t('districts', { defaultValue: '' }),
    wards: I18n.t('wards', { defaultValue: '' }),
    please_select_province: I18n.t('please_select_province', {
      defaultValue: '',
    }),
    please_select_districts: I18n.t('please_select_districts', {
      defaultValue: '',
    }),
    please_select_wards: I18n.t('please_select_wards', { defaultValue: '' }),
    address_detail: I18n.t('address_detail', { defaultValue: '' }),
    delete_successfully: I18n.t('delete_successfully', { defaultValue: '' }),
    you_want_delete_receiver_info: I18n.t('you_want_delete_receiver_info', {
      defaultValue: '',
    }),
    you_want_delete_address: I18n.t('you_want_delete_address', {
      defaultValue: '',
    }),
    error_try_again: I18n.t('error_try_again', { defaultValue: '' }),
    save_successfully: I18n.t('save_successfully', { defaultValue: '' }),
    please_input_fullname: I18n.t('please_input_fullname', {
      defaultValue: '',
    }),
    please_input_phone: I18n.t('please_input_phone', { defaultValue: '' }),
    do_you_want_delete_product: I18n.t('do_you_want_delete_product', {
      defaultValue: '',
    }),
    do_you_want_delete_all_cart: I18n.t('do_you_want_delete_all_cart', {
      defaultValue: '',
    }),
    delete_product_successfully: I18n.t('delete_product_successfully', {
      defaultValue: '',
    }),
    delete_all_cart: I18n.t('delete_all_cart', { defaultValue: '' }),
    phone_not_validate: I18n.t('phone_not_validate', { defaultValue: '' }),
    please_input_address: I18n.t('please_input_address', { defaultValue: '' }),
    you_want_support: I18n.t('you_want_support', { defaultValue: '' }),
    not_update: I18n.t('not_update', { defaultValue: '' }),
    select_area: I18n.t('select_area', { defaultValue: '' }),
    account_not_in_system: I18n.t('account_not_in_system', {
      defaultValue: '',
    }),
    continue: I18n.t('continue', { defaultValue: '' }),
    see_less: I18n.t('see_less', { defaultValue: '' }),
    product_related: I18n.t('product_related', { defaultValue: '' }),
    please_input_password: I18n.t('please_input_password', {
      defaultValue: '',
    }),
    support: I18n.t('support', { defaultValue: '' }),
    product_detail: I18n.t('product_detail', { defaultValue: '' }),
    accumulation_point: I18n.t('accumulation_point', { defaultValue: '' }),
    copy_order_code_successfully: I18n.t('copy_order_code_successfully', {
      defaultValue: '',
    }),
    history: I18n.t('history', { defaultValue: '' }),
    male: I18n.t('male', { defaultValue: '' }),
    not_allow_empty: I18n.t('not_allow_empty', { defaultValue: '' }),
    not_duplicate_password_now: I18n.t('not_duplicate_password_now', {
      defaultValue: '',
    }),
    not_less_than_6_character: I18n.t('not_less_than_6_character', {
      defaultValue: '',
    }),
    not_exceed_21_character: I18n.t('not_exceed_21_character', {
      defaultValue: '',
    }),
    not_duplicate: I18n.t('not_duplicate', { defaultValue: '' }),
    female: I18n.t('female', { defaultValue: '' }),
    gender: I18n.t('gender', { defaultValue: '' }),
    choose_day: I18n.t('choose_day', { defaultValue: '' }),
    readAll: I18n.t('readAll', { defaultValue: '' }),
    birtday: I18n.t('birtday', { defaultValue: '' }),
    manager_debit: I18n.t('manager_debit', { defaultValue: '' }),
    select_birtday: I18n.t('select_birtday', { defaultValue: '' }),
    copy_banking_number_successfully: I18n.t(
      'copy_banking_number_successfully',
      { defaultValue: '' }
    ),
    copy_banking_content_successfully: I18n.t(
      'copy_banking_content_successfully',
      { defaultValue: '' }
    ),
    select_gender: I18n.t('select_gender', { defaultValue: '' }),
    please_input_birtday: I18n.t('please_input_birtday', { defaultValue: '' }),
    bank: I18n.t('bank', { defaultValue: '' }),
    receiver: I18n.t('receiver', { defaultValue: '' }),
    save_code: I18n.t('save_code', { defaultValue: '' }),
    content_banking: I18n.t('content_banking', { defaultValue: '' }),
    or_scan_qr: I18n.t('or_scan_qr', { defaultValue: '' }),

    banking_policy: I18n.t('banking_policy', { defaultValue: '' }),
    policy_and_infomation: I18n.t('policy_and_infomation', {
      defaultValue: '',
    }),
    send_successfully: I18n.t('send_successfully', { defaultValue: '' }),
    completed: I18n.t('completed', { defaultValue: '' }),
    confirmed: I18n.t('confirmed', { defaultValue: '' }),
    pending: I18n.t('pending', { defaultValue: '' }),
    not_use: I18n.t('not_use', { defaultValue: '' }),
    used: I18n.t('used', { defaultValue: '' }),
    expried: I18n.t('expried', { defaultValue: '' }),
    not_to_expiry: I18n.t('not_to_expiry', { defaultValue: '' }),
    not_expried: I18n.t('not_expried', { defaultValue: '' }),
    quota_expried: I18n.t('quota_expried', { defaultValue: '' }),
    not_quota_expried: I18n.t('not_quota_expried', { defaultValue: '' }),
    addToCart: I18n.t('addToCart', { defaultValue: '' }),
    delete_all: I18n.t('delete_all', { defaultValue: '' }),
    selected: I18n.t('selected', { defaultValue: '' }),
    memo: I18n.t('memo', { defaultValue: '' }),
    add_memo: I18n.t('add_memo', { defaultValue: '' }),
    password_old: I18n.t('password_old', { defaultValue: '' }),
    password_new: I18n.t('password_new', { defaultValue: '' }),
    password_confirm: I18n.t('password_confirm', { defaultValue: '' }),
    update: I18n.t('update', { defaultValue: '' }),
    detail: I18n.t('detail', { defaultValue: '' }),
    logout: I18n.t('logout', { defaultValue: '' }),
    await_goods: I18n.t('await_goods', { defaultValue: '' }),
    order_info: I18n.t('order_info', { defaultValue: '' }),
    order_code: I18n.t('order_code', { defaultValue: '' }),
    transport_info: I18n.t('transport_info', { defaultValue: '' }),
    being_transport: I18n.t('being_transport', { defaultValue: '' }),
    shiped: I18n.t('shiped', { defaultValue: '' }),
    discount: I18n.t('discount', { defaultValue: '' }),
    total_payment: I18n.t('total_payment', { defaultValue: '' }),
    order_detail: I18n.t('order_detail', { defaultValue: '' }),
    oldest: I18n.t('oldest', { defaultValue: '' }),
    amount_hot: I18n.t('amount_hot', { defaultValue: '' }),
    amount_sale: I18n.t('amount_sale', { defaultValue: '' }),
    apply: I18n.t('apply', { defaultValue: '' }),
    add_flash: I18n.t('add_flash', { defaultValue: '' }),
    send_request_support_successfully: I18n.t(
      'send_request_support_successfully',
      { defaultValue: '' }
    ),
    loading: I18n.t('loading', { defaultValue: '' }),
    newest: I18n.t('newest', { defaultValue: '' }),
    price_min_to_max: I18n.t('price_min_to_max', { defaultValue: '' }),
    price_max_to_min: I18n.t('price_max_to_min', { defaultValue: '' }),
    all: I18n.t('all', { defaultValue: '' }),
    advance_filter: I18n.t('advance_filter', { defaultValue: '' }),
    cancel_filter: I18n.t('cancel_filter', { defaultValue: '' }),
    infomation: I18n.t('infomation', { defaultValue: '' }),
    sort_follwing: I18n.t('sort_follwing', { defaultValue: '' }),
    apply_all_product: I18n.t('apply_all_product', { defaultValue: '' }),
    start_time: I18n.t('start_time', { defaultValue: '' }),
    apply_promo: I18n.t('apply_promo', { defaultValue: '' }),
    description: I18n.t('description', { defaultValue: '' }),
    promo_detail: I18n.t('promo_detail', { defaultValue: '' }),
    order_amount: I18n.t('order_amount', { defaultValue: '' }),
    please_add_receiver: I18n.t('please_add_receiver', { defaultValue: '' }),
    my_address: I18n.t('my_address', { defaultValue: '' }),
    guide_order: I18n.t('guide_order', { defaultValue: '' }),
    select_payments_type: I18n.t('select_payments_type', { defaultValue: '' }),
    change_info_account_success: I18n.t('change_info_account_success', {
      defaultValue: '',
    }),
    apply_total_order: I18n.t('apply_total_order', { defaultValue: '' }),
    apply_only_product: I18n.t('apply_only_product', { defaultValue: '' }),
    setting: I18n.t('setting', { defaultValue: '' }),
    change_password_successfully: I18n.t('change_password_successfully', {
      defaultValue: '',
    }),
    do_you_cancel_account: I18n.t('do_you_cancel_account', {
      defaultValue: '',
    }),
    change_password: I18n.t('change_password', { defaultValue: '' }),
    cancle_link_account_successfully: I18n.t(
      'cancle_link_account_successfully',
      { defaultValue: '' }
    ),
    updating: I18n.t('updating', { defaultValue: '' }),
    cancel_order: I18n.t('cancel_order', { defaultValue: '' }),
    add_product_successfully: I18n.t('add_product_successfully', {
      defaultValue: '',
    }),
    number_left: I18n.t('number_left', { defaultValue: '' }),
    do_you_want_discount_code: I18n.t('do_you_want_discount_code', {
      defaultValue: '',
    }),
    discount_code: I18n.t('discount_code', { defaultValue: '' }),
    do_you_want_delete_address: I18n.t('do_you_want_delete_address', {
      defaultValue: '',
    }),
  }
}
export default strings
